services:
  postgres:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mendax47
      POSTGRES_DB: LearnSpringBoot
    volumes:
      - DB:/data/postgres
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  DB: